name: rules

on:
  workflow_dispatch: {}
  pull_request:
    types:
      - auto_merge_enabled

jobs:
  require_merge_commit_on_merge_PR:
    name: Merge PRs (from our merge script) must create merge commits
    if: ${{ contains(github.head_ref, '/merge-') && github.pull_request.merge_method != 'merge' }}
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
