name: rules

on:
  workflow_dispatch: {}
  pull_request:
    types:
      - auto_merge_enabled

jobs:
  require_merge_commit_on_merge_PR:
    name: Merge script PRs must create merge commits
    if: ${{ contains(github.head_ref, '/merge-') }}
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - run: |
          if ${{ github.event.pull_request.auto_merge.merge_method != 'merge' }}; then
            exit 1
          fi
